spring:

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5460/${POSTGRES_DATABASE:db}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:pswd}

  jpa:
    hibernate:
      ddl-auto: validate
    profiles:
      hibernate:
        format_sql: true
        show_sql: true
