version: '3.9'

services:
  postgres:
    container_name: file-loader-app
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pswd
    ports:
      - "5460:5460"
    command: -p 5460
    restart: on-failure